### ISSUE TITLE
request : asset search 7z file download support

### ISSUE THREAD

**Issue by listelin** [UuuNyaa/blender_mmd_uuunyaa_tools#10]
asset searchで7zファイルもサポートしていただきたいです。（優先度は低い？）

いくつかサンプルを試そうと思ったのですがほとんどがパスワード付きか、7zかMega upload（直リンク不可）でした。
（パスワードは直接ダウンロードしてほしくないという意向なのでしょうがないですが）

https://github.com/UuuNyaa/blender_mmd_assets/issues/15

**Comment by UuuNyaa** [comment]
早速使ってくれてありがとうございます。
7z形式に対応してみます。

ちなみに、 import_action の `unzip`, `unrar` アクションは `password` という引数を取ることができます。

Thank you for using it so quickly.
I will try to support the 7z format.

By the way, the `unzip` and `unrar` actions of import_action can take a `password` argument.

**Example code**
```python
unzip(f'{file}',encoding='cp932',password='secret'); import_pmx('EL-F3U-Quelle/クウェレ.pmx',scale=0.08)
```

**Comment by UuuNyaa** [comment]
ローカル環境でアセットをテストするには、以下のようなJSONファイルを作成してください。
そして、 **Asset JSONs Folder** に配置してください。

To test the assets in your local environment, create a JSON file like below.
And place it in the **Asset JSONs Folder**.

see: https://github.com/UuuNyaa/blender_mmd_uuunyaa_tools/wiki#Preferences

```JSON
{
  "format": "blender_mmd_assets:2",
  "description": "This file is a release asset of blender_mmd_assets",
  "license": "CC-BY-4.0 License",
  "created_at": "2021-03-01T11:01:54Z",
  "asset_count": 1,
  "assets": [
    {
      "id": "00015",
      "type": "MODEL_MMD",
      "url": "https://api.github.com/repos/UuuNyaa/blender_mmd_assets/issues/15",
      "name": "Quelle",
      "tags": {
        "Female": "Female / 女性",
      },
      "updated_at": "2021-02-28T22:15:02Z",
      "thumbnail_url": "https://camo.githubusercontent.com/8c00f1c570a4b297b870851dbfc08ec2555e07454ff6ee352e9892df9c560ea6/68747470733a2f2f7374617469632e7769787374617469632e636f6d2f6d656469612f6236636238385f62666361353038316362616634373738626233333737363336346161646664617e6d76322e6a70672f76312f66696c6c2f775f3237392c685f3236312c616c5f632c715f38302c75736d5f302e36365f312e30305f302e30312f6633755f666163652e77656270",
      "download_url": "http://www.mediafire.com/file/5aolg2cjpgcily7/file",
      "import_action": "unzip(f'{file}',encoding='cp932',password='secret'); import_pmx('EL-F3U-Quelle/クウェレ.pmx',scale=0.08)",
      "aliases": {
        "en": "Quelle",
        "zh": "空 / Kōng",
        "ja": "クウェレ"
      },
      "note": "** THIS ENTRY CAN'T BE SEARCHED. 7z file problem?"
    }
  ]
}
```

**Comment by UuuNyaa** [comment]
@listelin おまたせしました。

7-zip形式に対応しました。
あらかじめ7-zipをインストールしておく必要があります。
Windows環境で動作確認をしていただけるとありがたいです。

7-zip format is now supported.
You need to have 7-zip installed in advance.
I would be grateful if you could check the operation in a Windows environment.

**Comment by listelin** [comment]
ありがとうございました。
blender 2.92/Windows10 7zip.exeでも動作を確認しました。

またパスが通っていない状態でのシステムコンソールエラーメッセージも出ることを確認しました。

また、テストとして背景アセットを追加してみましたが、背景タグの体系について適切でなければ修正お願いいたします。
https://github.com/UuuNyaa/blender_mmd_assets/issues/45

**Comment by UuuNyaa** [comment]
動作確認ありがとうございました。

背景タグの体系を少し変えました。
最終的には TurboSquid 等のモデル販売サイトのようなタグ構造になるかもしれませんね。

https://www.turbosquid.com/3d-models/3d-model-room-interior-1287247

Thank you for confirming the operation.

I've changed the background tag structure a bit.
Eventually, it may have a tag structure like a model sales site such as TurboSquid.
