### ISSUE TITLE
Write a wiki on how to add asset issues

### ISSUE THREAD

**Issue by UuuNyaa** [UuuNyaa/blender_mmd_uuunyaa_tools#13]
1. create a issue to https://github.com/UuuNyaa/blender_mmd_assets/issues
2. download the issue (eg. 15) in debug mode on UuuNyaa Assets Operator panel.
![image](https://user-images.githubusercontent.com/70152495/110135342-c0419780-7e11-11eb-84ee-dd578c304a87.png)

3. do debug
4. delete debug asset on UuuNyaa Assets Operator panel.

**Comment by listelin** [comment]
上の手順、確認できました。(7zはzipではないので解凍できないという想定通りのエラー）

https://github.com/UuuNyaa/blender_mmd_assets のGet latest assets.jsonしてローカルのassets.jsonを更新するUIは（今のところは）未実装ということでしょうか（もしくはassets.jsonも本体リリースと同梱して配布予定？）

**Comment by UuuNyaa** [comment]
[Preferences](https://github.com/UuuNyaa/blender_mmd_uuunyaa_tools/wiki#preferences)の ***Update Asset JSON*** ボタンでアセットを更新できます。
ただし、次のフィルタ条件にマッチするIssueのみが更新されます。
```{'state': 'open', 'milestone': 1, 'labels': 'Official'}```
デバッグ用途で任意のフィルタ条件で更新するには次のスクリプトをPython Consoleで実行してください。

You can update assets by clicking the ***Update Asset JSON*** button in [Preferences](https://github.com/UuuNyaa/blender_mmd_uuunyaa_tools/wiki#preferences).
However, only issues that match the following filter conditions will be updated.
```{'state': 'open', 'milestone': 1, 'labels': 'Official'}```
For debugging purposes, you can run the following script in the Python Console to update with any filter condition.

```python
# eg. Update all open assets
bpy.ops.mmd_uuunyaa_tools.update_asset_json(query="{'state': 'open'}")
bpy.ops.mmd_uuunyaa_tools.reload_asset_jsons()
```

**Comment by listelin** [comment]
了解しました。ありがとうございます

プリファレンスのボタン忘れがちですねｗ
設定のアップデートなので合理的ですが

**Comment by UuuNyaa** [comment]
たしかにプリファレンスは見落としやすいですね。
UuuNyaa Asset Searchパネルに***Reload Asset JSONs***と***Update Asset JSON***を追加しようと思います。

You're right, preferences are easy to overlook.
I am going to add ***Reload Asset JSONs*** and ***Update Asset JSON*** to the UuuNyaa Asset Search panel.

**Comment by UuuNyaa** [comment]
Panel added on Release v0.2.2!
![image](https://user-images.githubusercontent.com/70152495/110135342-c0419780-7e11-11eb-84ee-dd578c304a87.png)

**Comment by UuuNyaa** [comment]
I wrote: https://github.com/UuuNyaa/blender_mmd_uuunyaa_tools/wiki/How-to-add-a-new-asset

**Comment by listelin** [comment]
Wiki・動画お疲れ様です。
サンプルの陽菜も可愛いしレンダリングも綺麗ですねｗ

1点、手順にあるラベル付けやマイルストーンの設定はオーナーやコラボレーター以外できないようです。
ラベルについては管理としてUuuNyaaさんが一括してやるか、申請により許可するかなど考える必要がありそうです。

**Comment by UuuNyaa** [comment]
@listelin をコラボレーターとして招待しました。

ラベルとマイルストーンの付与に権限が必要なんですね。
アセットを追加してくれた人にはIssueコメントで申請するようにWikiを編集します。

I see that we need permissions to add labels and milestones.
I'll edit the wiki so that people who add assets can apply for them via Issue comments.

**Comment by listelin** [comment]
ありがとうございます。

invitatinをacceptして、ラベル・マイルストーン設定が可能になったことを確認しました。
