### ISSUE TITLE
UuuNyaa Asset Operator > Update Assets JSON button works only Official Label

### ISSUE THREAD

**Issue by listelin** [UuuNyaa/blender_mmd_uuunyaa_tools#17]
アセット追加後、milestoneをpublic assetにし、Update Assets JSONを実行しても、Queryで表示されません
https://github.com/UuuNyaa/blender_mmd_assets/issues/45

Update Asset JSONを実行した場合、以下のクエリが飛びますが、labels=Officialは不要ではないでしょうか？

https://api.github.com:443 "GET /repos/UuuNyaa/blender_mmd_assets/issues?state=open&milestone=1&labels=Official&per_page=100&page=1 HTTP/1.1" 200 None

**Comment by UuuNyaa** [comment]
指摘ありがとうございます。
日本の友人からの助言に従って、わざとそうしています。

日本のファンアートコミュニティではモデルの扱いに対して非常に過敏と聞いています。
そのため、デフォルトの設定では公式モデルやモデラーさんの正式配布物にのみが利用できるようにしました。
改造モデルへのアクセスは使用者自身の操作を要求する二段階方式にしてあります。
(少なくとも、Wikiに操作方法を書こうと思っています)

あなたはどう思いますか？

Thanks for pointing that out.
I did that on purpose, following the advice from my Japanese friends.

I've heard that the fan art community in Japan is very sensitive about how models are treated.
For this reason, the default setting is only available for official models and official distributions by modelers.
Access to the modified model is a two-step process that requires the user to perform the operation themselves.
(At least, I'm going to write the operating instructions on the Wiki)

What do you think?

**Comment by listelin** [comment]
ありがとうございます。
意図的な仕様であることについて了解しました。

**Comment by UuuNyaa** [comment]
Wikiに操作方法を追記しました。
I've added the instructions to the wiki.

https://github.com/UuuNyaa/blender_mmd_uuunyaa_tools/wiki#how-to-use-unofficial-assets
