### ISSUE TITLE
🐛 Bug When trying to integrates armatures with Koikatsu pmx exported model

### ISSUE THREAD

**Issue by OneGraves** [UuuNyaa/blender_mmd_uuunyaa_tools#23]
When exporting a Koikatsu model into pmx, then importing it to blender. When i watn to integrate the rigify rig to the mmd armature i have this error call :
Python: Traceback (most recent call last):
  File "C:\Users\OneGraves\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\mmd_uuunyaa_tools\editors\operators.py", line 227, in execute
    rigify_armature_object.imitate_mmd_bone_structure(mmd_armature_object)
  File "C:\Users\OneGraves\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\mmd_uuunyaa_tools\editors\armatures.py", line 1967, in imitate_mmd_bone_structure
    eye_height_translation_vector = Vector([0.0, 0.0, mmd_edit_bones['左目'].head[2] - rig_edit_bones['ORG-eye.L'].head[2]])
KeyError: '左目'

location: <unknown location>:-1

**Comment by UuuNyaa** [comment]
@OneGraves Thanks for the report.
It seems that there are not enough bones (eg. 左目, 右目, ...) that the MMD model should have.
Can you share the pmx file you used with me to investigate the cause?

**Comment by UuuNyaa** [comment]
@OneGraves Thanks for sharing.

**Comment by UuuNyaa** [comment]
@OneGraves I've solved the problem.
Fixed release is https://github.com/UuuNyaa/blender_mmd_uuunyaa_tools/releases/tag/v0.5.5

You can load the motion in the following steps.

1. Add metarig with **Clean Koikatsu Armature** check
![add_metarig](https://user-images.githubusercontent.com/70152495/118127529-c7e67380-b434-11eb-89a8-19b74c430708.gif)
2. **Integrate Armatures** and then **Apply MMD rest pose**
![integrate_and_pose](https://user-images.githubusercontent.com/70152495/118127523-c61cb000-b434-11eb-8328-81e5451bc963.gif)
3. load a motion
![move](https://user-images.githubusercontent.com/70152495/118127504-bf8e3880-b434-11eb-98a0-a5d913fc6f34.gif)

Shape keys is not supported.
How do you use the shape keys in koikatsu exported models?

**Comment by OneGraves** [comment]
Shape keys in koikatsu are a bit broken and need to be remade In blender
(new shape keys from mix). But thanks a lot for the fix 😃
