### ISSUE TITLE
Duplicate "UuuNyaa Extras" menu appears when updated to 0.6.2 -> Reinstallation solved the problem.

### ISSUE THREAD

**Issue by listelin** [UuuNyaa/blender_mmd_uuunyaa_tools#27]
軽微な問題なので修正不要です。同様の問題が出た人のための記録用です。
UuuNyaa Extrasが重複して表示される場合、一旦uuunyaa_toolsを削除して再起動、再インストール・再起動すれば正常になります。

![update](https://user-images.githubusercontent.com/44924233/119951605-179d7100-bfd7-11eb-9216-b276e389cef2.jpg)

Blender 2.92 /Windows 10

**Comment by UuuNyaa** [comment]
報告ありがとうございます。
v0.6.1 -> v0.6.2 の変更でメニューアイテムの名前を変えたことが原因だと思います。

Thanks for the report.
I think the reason is that I changed the name of menu item in v0.6.1 -> v0.6.2.
