### ISSUE TITLE
asset search #67 unrar -> 0 bytes files.(possible password problem?)

### ISSUE THREAD

**Issue by listelin** [UuuNyaa/blender_mmd_uuunyaa_tools#29]
Blender 2.92/Windows10

https://github.com/UuuNyaa/blender_mmd_assets/issues/67
・Downloadは正常に完了します（キャッシュファイルをwinrarで解凍しパスワードを手動で入力すると正常に解凍できます）
・しかし、Importしようとするとサイズが０バイトになっており、インポートできません。

![Alicia-broken](https://user-images.githubusercontent.com/44924233/120008336-d4aebe00-c015-11eb-8498-80418303b3ee.jpg)

log-------------------------------------------
https://downloadx.getuploader.com:443 "GET /g/60b10b34-3610-4ba8-a813-7017a010e467/yy_w/2/ask.rar HTTP/1.1" 200 40812067
done: Alicia, 00067, State.CACHED, 815ae810738c9dc11e85dd3b66fa09f08917317a
_save_contents: 52 to C:\Users\a\AppData\Local\Temp\mmd_uuunyaa_tools_cache\contents.json
do: MMD_UUUNYAA_TOOLS_OT_asset_import

unrar(C:\Users\a\AppData\Local\Temp\mmd_uuunyaa_tools_cache\815ae810738c9dc11e85dd3b66fa09f08917317a,C:\Users\a\BlenderAssets\MODEL_MMD/00067.Alicia,C:\Users\a\BlenderAssets\MODEL_MMD/00067.Alicia\00067.json)

Failed the read enough data: req=3701 got=0
Failed the read enough data
Corrupt file - CRC check failed: 繧｢繝ｪ繧ｷ繧｢繝ｻ繧ｽ繝ｪ繝・ラ謾ｹ/readme.txt - exp=2987717629 got=0
Failed the read enough data: req=16384 got=0
Failed the read enough data
Corrupt file - CRC check failed: 繧｢繝ｪ繧ｷ繧｢繝ｻ繧ｽ繝ｪ繝・ラ謾ｹ/繧｢繝ｪ繧ｷ繧｢繝ｻ繧ｽ繝ｪ繝・ラ謾ｹMB.pmx - exp=3436643439 got=0
Failed the read enough data: req=16384 got=0
(中略）
Failed the read enough data
Corrupt file - CRC check failed: 繧｢繝ｪ繧ｷ繧｢繝ｻ繧ｽ繝ｪ繝・ラ謾ｹ/繝・け繧ｹ繝√Ε/mb2.tga - exp=1327389014 got=0

**Comment by UuuNyaa** [comment]
報告ありがとうございます。
調査してみます。

私のLinux環境では展開できました。
おそらく文字コードの問題だと思います。

Thanks for the report.
I'll look into it.

I was able to extract it successfully in my Linux environment.
I think it's probably a character encoding issue.

**Comment by UuuNyaa** [comment]
@listelin 
文字コードの問題ではありませんでした。
(UuuNyaa/blender_mmd_assets#67 の rar ファイルは Unicode ファイル名が格納されていました)
デバッグ用のWindows環境を準備しようと思います。
使っているWinRARのバージョンを教えてください。

It wasn't a character encoding problem.
(The Unicode file name was stored in the rar file of UuuNyaa/blender_mmd_assets#67 )
I will prepare a Windows environment for debugging.
What version of WinRAR are you using?

**Comment by listelin** [comment]
WinRar 6.01 (64bit)です。

・環境を準備するのは大変だと思いますので、何か確認すべきことなどあれば言っていただければ対応します。
　デバッグ文を仕込んで確認など（pythonをさわったことはないのですが・・・）

・キャッシュなどを全削除して確認しましたが再現します。
・コマンドラインで、キャッシュファイルにrar拡張子を付与すれば以下のように問題なく解凍できました。
---
C:\tmp>unrar x -pmmd 815ae810738c9dc11e85dd3b66fa09f08917317a.rar

UNRAR 6.01 x64 フリーウェア      Copyright (C) 1993-2021 Alexander Roshal


815ae810738c9dc11e85dd3b66fa09f08917317a.rar から解凍しています

作成中    アリシア・ソリッド改                                                OK
解凍中  アリシア・ソリッド改\readme.txt                                     OK
解凍中  アリシア・ソリッド改\アリシア・ソリッド改MB.pmx                               OK
解凍中  アリシア・ソリッド改\アリシア・ソリッド改MB2P.pmx                             OK
解凍中  アリシア・ソリッド改\アリシア・ソリッド改フリル.pmx                              OK
解凍中  アリシア・ソリッド改\アリシア・ソリッド改フリル2P.pmx                            OK
解凍中  アリシア・ソリッド改\アリシア・ソリッド改レオタード.pmx                            OK
解凍中  アリシア・ソリッド改\アリシア・ソリッド改レオタード2P.pmx                          OK
解凍中  アリシア・ソリッド改\アリシア・ソリッド改全部入り.pmx                             OK
解凍中  アリシア・ソリッド改\アリシア・ソリッド改全部入り2P.pmx                           OK
解凍中  アリシア・ソリッド改\アリシア・ソリッド改競泳.pmx                               OK
解凍中  アリシア・ソリッド改\アリシア・ソリッド改競泳2P.pmx                             OK
作成中    アリシア・ソリッド改\スフィア                                           OK
解凍中  アリシア・ソリッド改\スフィア\b5_s.bmp                                  OK
解凍中  アリシア・ソリッド改\スフィア\choker_s.png                              OK
解凍中  アリシア・ソリッド改\スフィア\eye_s.bmp                                 OK
解凍中  アリシア・ソリッド改\スフィア\hair_s.bmp                                OK
解凍中  アリシア・ソリッド改\スフィア\houseki_s.jpg                             OK
解凍中  アリシア・ソリッド改\スフィア\houseki_s2.jpg                            OK
解凍中  アリシア・ソリッド改\スフィア\mizugi_s.bmp                              OK
解凍中  アリシア・ソリッド改\スフィア\skin_s.bmp                                OK
解凍中  アリシア・ソリッド改\スフィア\tongue_s.bmp                              OK
作成中    アリシア・ソリッド改\テクスチャ                                          OK
解凍中  アリシア・ソリッド改\テクスチャ\Alicia_eye.tga                           OK
解凍中  アリシア・ソリッド改\テクスチャ\Alicia_eye2.tga                          OK
解凍中  アリシア・ソリッド改\テクスチャ\Alicia_face.tga                          OK
解凍中  アリシア・ソリッド改\テクスチャ\Alicia_face2.tga                         OK
解凍中  アリシア・ソリッド改\テクスチャ\Alicia_hair.tga                          OK
解凍中  アリシア・ソリッド改\テクスチャ\Alicia_hair2.tga                         OK
解凍中  アリシア・ソリッド改\テクスチャ\Alicia_other.tga                         OK
解凍中  アリシア・ソリッド改\テクスチャ\choker.bmp                               OK
解凍中  アリシア・ソリッド改\テクスチャ\choker2.bmp                              OK
解凍中  アリシア・ソリッド改\テクスチャ\desktop.ini                              OK
解凍中  アリシア・ソリッド改\テクスチャ\frill.tga                                OK
解凍中  アリシア・ソリッド改\テクスチャ\frill2.tga                               OK
解凍中  アリシア・ソリッド改\テクスチャ\hada.bmp                                 OK
解凍中  アリシア・ソリッド改\テクスチャ\hada2.bmp                                OK
解凍中  アリシア・ソリッド改\テクスチャ\kyouei.tga                               OK
解凍中  アリシア・ソリッド改\テクスチャ\kyouei2.tga                              OK
解凍中  アリシア・ソリッド改\テクスチャ\Leotard.tga                              OK
解凍中  アリシア・ソリッド改\テクスチャ\Leotard2.tga                             OK
解凍中  アリシア・ソリッド改\テクスチャ\mb.tga                                   OK
解凍中  アリシア・ソリッド改\テクスチャ\mb2.tga                                  OK
すべて OK

---
・最初のログと同じですが、文字化けしていないログも一応添付します。
_save_contents: 2 to C:\Users\a\AppData\Local\Temp\mmd_uuunyaa_tools_cache\contents.json
do: MMD_UUUNYAA_TOOLS_OT_asset_import
unrar(C:\Users\a\AppData\Local\Temp\mmd_uuunyaa_tools_cache\815ae810738c9dc11e85dd3b66fa09f08917317a,C:\Users\a\BlenderAssets\MODEL_MMD/00067.Alicia,C:\Users\a\BlenderAssets\MODEL_MMD/00067.Alicia\00067.json)
Failed the read enough data: req=3701 got=0
Failed the read enough data
Corrupt file - CRC check failed: アリシア・ソリッド改/readme.txt - exp=2987717629 got=0
Failed the read enough data: req=16384 got=0
Failed the read enough data
Corrupt file - CRC check failed: アリシア・ソリッド改/アリシア・ソリッド改MB.pmx - exp=3436643439 got=0
Failed the read enough data: req=16384 got=0
Failed the read enough data
Corrupt file - CRC check failed: アリシア・ソリッド改/アリシア・ソリッド改MB2P.pmx - exp=3085165652 got=0
Failed the read enough data: req=16384 got=0
Failed the read enough data
Corrupt file - CRC check failed: アリシア・ソリッド改/アリシア・ソリッド改フリル.pmx - exp=3062573784 got=0
Failed the read enough data: req=16384 got=0
Failed the read enough data
Corrupt file - CRC check failed: アリシア・ソリッド改/アリシア・ソリッド改フリル2P.pmx - exp=1678597543 got=0
Failed the read enough data: req=16384 got=0
Failed the read enough data
Corrupt file - CRC check failed: アリシア・ソリッド改/アリシア・ソリッド改レオタード.pmx - exp=10879650 got=0
Failed the read enough data: req=16384 got=0
Failed the read enough data
Corrupt file - CRC check failed: アリシア・ソリッド改/アリシア・ソリッド改レオタード2P.pmx - exp=78870757 got=0
Failed the read enough data: req=16384 got=0
Failed the read enough data
Corrupt file - CRC check failed: アリシア・ソリッド改/アリシア・ソリッド改全部入り.pmx - exp=4245270302 got=0
Failed the read enough data: req=16384 got=0
Failed the read enough data
Corrupt file - CRC check failed: アリシア・ソリッド改/アリシア・ソリッド改全部入り2P.pmx - exp=1069989106 got=0
Failed the read enough data: req=16384 got=0
Failed the read enough data
Corrupt file - CRC check failed: アリシア・ソリッド改/アリシア・ソリッド改競泳.pmx - exp=2113166809 got=0
Failed the read enough data: req=16384 got=0
Failed the read enough data
Corrupt file - CRC check failed: アリシア・ソリッド改/アリシア・ソリッド改競泳2P.pmx - exp=3629036551 got=0
Failed the read enough data: req=16384 got=0
Failed the read enough data
Corrupt file - CRC check failed: アリシア・ソリッド改/スフィア/b5_s.bmp - exp=2550177477 got=0
Failed the read enough data: req=16384 got=0
Failed the read enough data
Corrupt file - CRC check failed: アリシア・ソリッド改/スフィア/choker_s.png - exp=2581095479 got=0
Failed the read enough data: req=16384 got=0
Failed the read enough data
Corrupt file - CRC check failed: アリシア・ソリッド改/スフィア/eye_s.bmp - exp=3186330806 got=0
Failed the read enough data: req=16384 got=0
Failed the read enough data
Corrupt file - CRC check failed: アリシア・ソリッド改/スフィア/hair_s.bmp - exp=3097810780 got=0
Failed the read enough data: req=16384 got=0
Failed the read enough data
Corrupt file - CRC check failed: アリシア・ソリッド改/スフィア/houseki_s.jpg - exp=2451070590 got=0
Failed the read enough data: req=16384 got=0
Failed the read enough data
Corrupt file - CRC check failed: アリシア・ソリッド改/スフィア/houseki_s2.jpg - exp=2171617095 got=0
Failed the read enough data: req=16384 got=0
Failed the read enough data
Corrupt file - CRC check failed: アリシア・ソリッド改/スフィア/mizugi_s.bmp - exp=3284701853 got=0
Failed the read enough data: req=16384 got=0
Failed the read enough data
Corrupt file - CRC check failed: アリシア・ソリッド改/スフィア/skin_s.bmp - exp=3097810780 got=0
Failed the read enough data: req=16384 got=0
Failed the read enough data
Corrupt file - CRC check failed: アリシア・ソリッド改/スフィア/tongue_s.bmp - exp=3318776804 got=0
Failed the read enough data: req=16384 got=0
Failed the read enough data
Corrupt file - CRC check failed: アリシア・ソリッド改/テクスチャ/Alicia_eye.tga - exp=65436250 got=0
Failed the read enough data: req=16384 got=0
Failed the read enough data
Corrupt file - CRC check failed: アリシア・ソリッド改/テクスチャ/Alicia_eye2.tga - exp=4036432835 got=0
Failed the read enough data: req=16384 got=0
Failed the read enough data
Corrupt file - CRC check failed: アリシア・ソリッド改/テクスチャ/Alicia_face.tga - exp=3865596152 got=0
Failed the read enough data: req=16384 got=0
Failed the read enough data
Corrupt file - CRC check failed: アリシア・ソリッド改/テクスチャ/Alicia_face2.tga - exp=728601547 got=0
Failed the read enough data: req=16384 got=0
Failed the read enough data
Corrupt file - CRC check failed: アリシア・ソリッド改/テクスチャ/Alicia_hair.tga - exp=2046525928 got=0
Failed the read enough data: req=16384 got=0
Failed the read enough data
Corrupt file - CRC check failed: アリシア・ソリッド改/テクスチャ/Alicia_hair2.tga - exp=2140101017 got=0
Failed the read enough data: req=16384 got=0
Failed the read enough data
Corrupt file - CRC check failed: アリシア・ソリッド改/テクスチャ/Alicia_other.tga - exp=2652202024 got=0
Failed the read enough data: req=16384 got=0
Failed the read enough data
Corrupt file - CRC check failed: アリシア・ソリッド改/テクスチャ/choker.bmp - exp=3957649466 got=0
Failed the read enough data: req=16384 got=0
Failed the read enough data
Corrupt file - CRC check failed: アリシア・ソリッド改/テクスチャ/choker2.bmp - exp=3934118248 got=0
Failed the read enough data: req=46 got=0
Failed the read enough data
Corrupt file - CRC check failed: アリシア・ソリッド改/テクスチャ/desktop.ini - exp=3514054565 got=0
Failed the read enough data: req=16384 got=0
Failed the read enough data
Corrupt file - CRC check failed: アリシア・ソリッド改/テクスチャ/frill.tga - exp=3429639501 got=0
Failed the read enough data: req=16384 got=0
Failed the read enough data
Corrupt file - CRC check failed: アリシア・ソリッド改/テクスチャ/frill2.tga - exp=1430899173 got=0
Failed the read enough data: req=16384 got=0
Failed the read enough data
Corrupt file - CRC check failed: アリシア・ソリッド改/テクスチャ/hada.bmp - exp=2619335906 got=0
Failed the read enough data: req=16384 got=0
Failed the read enough data
Corrupt file - CRC check failed: アリシア・ソリッド改/テクスチャ/hada2.bmp - exp=1756483349 got=0
Failed the read enough data: req=16384 got=0
Failed the read enough data
Corrupt file - CRC check failed: アリシア・ソリッド改/テクスチャ/kyouei.tga - exp=1492061922 got=0
Failed the read enough data: req=16384 got=0
Failed the read enough data
Corrupt file - CRC check failed: アリシア・ソリッド改/テクスチャ/kyouei2.tga - exp=1219913938 got=0
Failed the read enough data: req=16384 got=0
Failed the read enough data
Corrupt file - CRC check failed: アリシア・ソリッド改/テクスチャ/Leotard.tga - exp=3060548137 got=0
Failed the read enough data: req=16384 got=0
Failed the read enough data
Corrupt file - CRC check failed: アリシア・ソリッド改/テクスチャ/Leotard2.tga - exp=3404328075 got=0
Failed the read enough data: req=16384 got=0
Failed the read enough data
Corrupt file - CRC check failed: アリシア・ソリッド改/テクスチャ/mb.tga - exp=422297241 got=0
Failed the read enough data: req=16384 got=0
Failed the read enough data
Corrupt file - CRC check failed: アリシア・ソリッド改/テクスチャ/mb2.tga - exp=1327389014 got=0
import_pmx(アリシア・ソリッド改/アリシア・ソリッド改全部入り.pmx,0.0772190767,C:\Users\a\BlenderAssets\MODEL_MMD/00067.Alicia)

**Comment by UuuNyaa** [comment]
協力ありがとうございます。
他のrarファイルアセットでも同じ問題が発生するか確認してもらえますか？

https://github.com/UuuNyaa/blender_mmd_assets/issues?q=is%3Aissue+is%3Aopen+unrar


Thank you for the offer.
Can you check if the same problem occurs with other rar file assets?

https://github.com/UuuNyaa/blender_mmd_assets/issues?q=is%3Aissue+is%3Aopen+unrar

**Comment by listelin** [comment]
・上でキャッシュファイルに.rarを付与して解凍しましたが。付与しなくても問題ありませんでした
　unrar x -pmmd 815ae810738c9dc11e85dd3b66fa09f08917317a

・パスワードが誤って渡っている場合は以下のようでログが違いました
# 元々Linux環境でうまくいってるので考えにくい話ですが一応確認

---
C:\tmp>unrar x -pmmda 815ae810738c9dc11e85dd3b66fa09f08917317a.rar
作成中    アリシア・ソリッド改                                                OK
解凍中  アリシア・ソリッド改\readme.txt                                      0%
暗号化されたファイル アリシア・ソリッド改\readme.txt のチェックサムエラーが発生しました。ファイルが破損しているか、パスワードが正しくありません。
解凍中  アリシア・ソリッド改\アリシア・ソリッド改MB.pmx                                0%
暗号化されたファイル アリシア・ソリッド改\アリシア・ソリッド改MB.pmx のチェックサムエラーが発生しました。ファイルが破損しているか、パスワードが正しくありません。

**Comment by UuuNyaa** [comment]
たしかに、パスワード付きのrarはアリシアだけです。
パスワード問題を調べてみます。

Indeed, Alicia is the only RAR with a password.
I'll look into the password issue.

**Comment by listelin** [comment]
> 協力ありがとうございます。
> 他のrarファイルアセットでも同じ問題が発生するか確認してもらえますか？
> 
> https://github.com/UuuNyaa/blender_mmd_assets/issues?q=is%3Aissue+is%3Aopen+unrar

MEIも同じですね。
解答後のMei_definitive.blendが0バイトファイルになっています。

ということはパスワードではなさそうです。
---
https://na0.files.sfmlab.com:443 "GET /content/content/file/MEI_DEFINITIVE.rar?AWSAccessKeyId=YALKTSWDUPLBGUZZ&Signature=IsqWl2m9%2F%2FxSvWKyQh6ijoUkgSU%3D&Expires=1622268382 HTTP/1.1" 200 78542644
done: Mei, 00074, State.CACHED, bb0115622dd43b0b07d6b0525a3fba90c971c0ab
_save_contents: 4 to C:\Users\a\AppData\Local\Temp\mmd_uuunyaa_tools_cache\contents.json
do: MMD_UUUNYAA_TOOLS_OT_asset_import
unrar(C:\Users\a\AppData\Local\Temp\mmd_uuunyaa_tools_cache\bb0115622dd43b0b07d6b0525a3fba90c971c0ab,C:\Users\a\BlenderAssets\MODEL_BLENDER/00074.Mei,C:\Users\a\BlenderAssets\MODEL_BLENDER/00074.Mei\00074.json)
Failed the read enough data: req=16384 got=0
Failed the read enough data
Corrupt file - CRC check failed: Mei_definitive.blend - exp=2147163269 got=0
import_collections(Mei_definitive.blend,('Collection 1 Mei',),C:\Users\a\BlenderAssets\MODEL_BLENDER/00074.Mei)
警告: 「C:\Users\a\BlenderAssets\MODEL_BLENDER/00074.Mei\Mei_definitive.blend」を読み込みできません：不十分なコンテンツです
delete_objects(WGT-,None)
情報: 0個のオブジェクトを削除しました
delete_objects(WGTS-,None)
情報: 0個のオブジェクトを削除しました

**Comment by listelin** [comment]
https://github.com/UuuNyaa/blender_mmd_assets/issues/14
これら原神はunrarで問題ありませんでした

OK　原神いくつか
NG 　Alicia、MEI

**Comment by listelin** [comment]
全てのAsset Search関連のキャッシュ・フォルダを削除して再度MEIを確認しましたが、結果変わりませんでした。
https://github.com/UuuNyaa/blender_mmd_assets/issues/74

また、キャッシュファイルをコマンドラインで回答すると問題なく解凍できます。

---
C:\tmp>unrar x bb0115622dd43b0b07d6b0525a3fba90c971c0ab.rar

UNRAR 6.01 x64 フリーウェア      Copyright (C) 1993-2021 Alexander Roshal

bb0115622dd43b0b07d6b0525a3fba90c971c0ab.rar から解凍しています

解凍中  Mei_definitive.blend                                      OK
すべて OK

**Comment by UuuNyaa** [comment]
利用しているモジュール自体の問題( markokr/rarfile#10 )かもしれません。
unrar.exeを自分で起動する方式に変更してみます。

It may be a problem ( markokr/rarfile#10 ) with the module we are using.
I'll change the method to launch unrar.exe by self.

**Comment by UuuNyaa** [comment]
@listelin 
独自のランチャーで UnRAR.exe を呼び出すように修正しました。

最新コミット (04faab25bf87667acac4d36aeca26f4b316737aa) のファイルを次のように配置してテストしてもらえますか？
- 置換 mmd_uuunyaa_tools/asset_search/actions.py
- 追加 mmd_uuunyaa_tools/externals/xrarfile/xrarfile.py 

I have fixed to launch UnRAR.exe in its own launcher.
Could you test it by placing the files of latest commit (04faab25bf87667acac4d36aeca26f4b316737aa) as follows?
- Replace mmd_uuunyaa_tools/asset_search/actions.py
- Add mmd_uuunyaa_tools/externals/xrarfile/xrarfile.py

**Comment by listelin** [comment]
以下の２点を修正して正常に動作することを確認しました。

1 decode('utf-8') ->  decode('utf-8','ignore')  @ Line 103 , 109
```
  File "C:\Users\a\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\mmd_uuunyaa_tools\asset_search\panels.py", line 215, in execute
    ImportActionExecutor.execute_import_action(asset, content.filepath if content is not None else None)
  File "C:\Users\a\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\mmd_uuunyaa_tools\asset_search\actions.py", line 392, in execute_import_action
    **functions
  File "<source>", line 1, in <module>
  File "C:\Users\a\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\mmd_uuunyaa_tools\asset_search\actions.py", line 219, in unrar
    rar.extractall(path=asset_path, pwd=password)
  File "C:\Users\a\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\mmd_uuunyaa_tools\externals\xrarfile\xrarfile.py", line 297, in extractall
    password=pwd or self._pwd,
  File "C:\Users\a\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\mmd_uuunyaa_tools\externals\xrarfile\xrarfile.py", line 154, in execute_extractall
    for _ in self.execute(command):
  File "C:\Users\a\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\mmd_uuunyaa_tools\externals\xrarfile\xrarfile.py", line 103, in execute
    yield line.decode('utf-8').rstrip(linesep)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x83 in position 15: invalid start byte

location: <unknown location>:-1
エラー: Python: Traceback (most recent call last):
  File "C:\Users\a\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\mmd_uuunyaa_tools\asset_search\panels.py", line 215, in execute
    ImportActionExecutor.execute_import_action(asset, content.filepath if content is not None else None)
  File "C:\Users\a\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\mmd_uuunyaa_tools\asset_search\actions.py", line 392, in execute_import_action
    **functions
  File "<source>", line 1, in <module>
  File "C:\Users\a\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\mmd_uuunyaa_tools\asset_search\actions.py", line 219, in unrar
    rar.extractall(path=asset_path, pwd=password)
  File "C:\Users\a\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\mmd_uuunyaa_tools\externals\xrarfile\xrarfile.py", line 297, in extractall
    password=pwd or self._pwd,
  File "C:\Users\a\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\mmd_uuunyaa_tools\externals\xrarfile\xrarfile.py", line 154, in execute_extractall
    for _ in self.execute(command):
  File "C:\Users\a\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\mmd_uuunyaa_tools\externals\xrarfile\xrarfile.py", line 103, in execute
    yield line.decode('utf-8').rstrip(linesep)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x83 in position 15: invalid start byte

location: <unknown location>:-1
```

2 キャッシュファイルに.rar拡張子を手動で付与
![新しいビットマップ イメージ](https://user-images.githubusercontent.com/44924233/120089862-1b490900-c139-11eb-8470-c544ee057ee7.jpg)

確認したファイル
Alicia https://github.com/UuuNyaa/blender_mmd_assets/issues/67
MEI https://github.com/UuuNyaa/blender_mmd_assets/issues/74
Aether https://github.com/UuuNyaa/blender_mmd_assets/issues/1

**Comment by listelin** [comment]
補足
```
C:\tmp>unrar x 815ae810738c9dc11e85dd3b66fa09f08917317a

UNRAR 6.01 x64 フリーウェア      Copyright (C) 1993-2021 Alexander Roshal

815ae810738c9dc11e85dd3b66fa09f08917317a.rar を開けません
指定されたファイルが見つかりません。
解凍するファイルがありません
```
対処は一時的にシンボリックリンクを貼るとかでしょうかね

**Comment by UuuNyaa** [comment]
アーカイブファイル名を `815ae810738c9dc11e85dd3b66fa09f08917317a.*` または `815ae810738c9dc11e85dd3b66fa09f08917317a*` と指定すれば展開できるかもしれません。
Maybe we can extract the archive file by specifying its name as `815ae810738c9dc11e85dd3b66fa09f08917317a.*` or `815ae810738c9dc11e85dd3b66fa09f08917317a*` .

```
diff --git a/mmd_uuunyaa_tools/externals/xrarfile/xrarfile.py b/mmd_uuunyaa_tools/externals/xrarfile/xrarfile.py
index f56fdd5..1850e8a 100644
--- a/mmd_uuunyaa_tools/externals/xrarfile/xrarfile.py
+++ b/mmd_uuunyaa_tools/externals/xrarfile/xrarfile.py
@@ -146,7 +146,7 @@ class UnrarExecutor(_Executor):
         if other_options is not None:
             command.extend(other_options)
 
-        command.append(archive_name)
+        command.append(archive_name + '.*')
 
         if output_directory is not None:
             command.append(output_directory + ('' if output_directory.endswith(os.path.sep) else os.path.sep))
```

https://documentation.help/WinRAR/HELPCommandLineSyntax.htm

> If no archive extension is specified when extracting, WinRAR assumes .rar, so * means all archives with .rar extension. If you need to process all archives without extension, use *. mask. \*.\* mask selects all files. You can use wildcards in archive name in most operations, such as extraction, test and many others, but wildcards are not allowed when archiving and deleting.

**Comment by listelin** [comment]
上記修正で正常に動作しました

確認したファイル
Alicia UuuNyaa/blender_mmd_assets#67
MEI UuuNyaa/blender_mmd_assets#74
Lisa UuuNyaa/blender_mmd_assets#5

**Comment by UuuNyaa** [comment]
修正したものを v0.6.4 としてリリースしました。
The fixed version was released as v0.6.4.

https://github.com/UuuNyaa/blender_mmd_uuunyaa_tools/releases/tag/v0.6.4

**Comment by listelin** [comment]
ありがとうございました！

v0.6.4で正常動作を確認しました

確認したファイル
Alicia UuuNyaa/blender_mmd_assets#67
MEI UuuNyaa/blender_mmd_assets#74
Jean UuuNyaa/blender_mmd_assets#11
