### ISSUE TITLE
Add assets dynamically download feature

### ISSUE THREAD

**Issue by UuuNyaa** [UuuNyaa/blender_mmd_uuunyaa_tools#3]
Where to manage the asset list?
1. Manage it in github wiki? (pages per asset)
2. Manage it in Google Spreads?

What to manage for each asset?
1. Thumbnail image
2. Download URL
3. Asset type
4. Path to the asset in the asset delivery container (.zip, .blend, ...)

**Comment by listelin** [comment]
blender初心者なので的外れだったらすみません
blenderkitを使うとかどうでしょうか？
R18モデルがセーフかどうか分かりませんが。もしくはblenderkitのコード自体GPLなので修正して独自のサーバーを作るというのも手間とお金かかっちゃいますがありえなくはなさそう

**Comment by UuuNyaa** [comment]
提案ありがとう
(BlenderKitのソースコードを読んでみました)
BlenderKitに依存すると、モデルをBlenderKitへ再アップロードする必要があるため、ライセンスや配布責任などの法的リスクがあります
このリスクを回避するために、アセット索引(asset list)だけをツール側で管理し、モデル本体は配布元URLから毎回ダウンロードする手法を採用したいと考えています
たぶん、法的に検索エンジンのクローラーと同じ扱いになるはずです

また、アセット索引にはGithub Issuesが使いやすそうだと考えています
検索機能・タグ機能を備えており、しかも無料です ;-)

Thanks for the suggestion.
(I read the source code for BlenderKit)
Relying on BlenderKit involves legal risks such as licensing and distribution liability, as models need to be re-uploaded to BlenderKit.
To avoid the risk, I will like to adopt a method where only the asset list is managed by the tool, and the model itself is downloaded each time from the its distribution URL.
Maybe, it will be legally treated the same as a search engine crawler.
I also think that Github Issues will be easy to use for asset list.
It has search and tagging capabilities, and it's free ;-)

**Comment by UuuNyaa** [comment]
Github Issuesを試しに使ってみました。
BlenderのUIを作り始めました。

I tried to use Github Issues.
I started to make UI for Blender.

https://github.com/UuuNyaa/blender_mmd_assets/issues

[![preview](https://img.youtube.com/vi/VTg30ufYUUg/0.jpg)](https://youtu.be/VTg30ufYUUg)
