### ISSUE TITLE
How to completely delete the UuuNyaaAsset Search settings?　(Frequent key error log after saving startup file)

### ISSUE THREAD

**Issue by listelin** [UuuNyaa/blender_mmd_uuunyaa_tools#32]
アセットサーチを利用すると以下のエラーが頻発するようになりました。
恐らくデバッグ等で何か不正なデータが残っているものと思います。

以下のフォルダを完全に消してもこのエラーが解消しません。
AssetJSONs Folder
AssetCache Folder
Asset Extract Root Folder

https://github.com/UuuNyaa/blender_mmd_assets/issues/92
```
Python: Traceback (most recent call last):
  File "C:\Users\a\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\mmd_uuunyaa_tools\asset_search\panels.py", line 383, in draw
    box.template_icon(PREVIEWS[asset.thumbnail_url].icon_id, scale=6.0)
KeyError: 'https://user-images.githubusercontent.com/44924233/120057599-30616180-c07f-11eb-881d-201e7fb09860.png'

location: <unknown location>:-1
```

完全にUuuNyaaAsset Search の設定を消す方法を教えていただけないでしょうか？

Blender 2.92 / Windows10 / UuunyaaTools 0.6.4
* 他のPCのBlenderでは再現しません。
---

The following error occurs frequently when using asset search.
This is probably due to some invalid data left over from debugging.

This error does not go away even if I delete the following folders completely.
AssetJSONs Folder
AssetCache Folder
Asset Extract Root Folder

* This error is not reproduced by Blender on other computers.

Can you please tell me how to completely delete the UuuNyaaAsset Search settings?

**Comment by listelin** [comment]
上記エラーについて、Debug issue が92から変更できないことも関係があるかもしれません
入力では変更できますが、再起動するとまた92に戻ります

As for the above error, it may be related to the fact that the Debug issue cannot be changed from 92.
I can change it by typing it in, but when I reboot, it goes back to 92 again.

![debug_number_cant_change](https://user-images.githubusercontent.com/44924233/120186691-ca2b3900-c24e-11eb-8b11-d9a1b93f24a3.jpg)

**Comment by UuuNyaa** [comment]
Asset Search の条件は .blend ファイルに保存されるようです。
起動時のデフォルト値は File > Defaults > Save Startup File で上書きできます。
プロパティを保存しないようにする方法を検討してみます。

Asset Search properties seem to be saved in a .blend file.
The default values at startup can be overridden by File > Defaults > Save Startup File.
I will look into ways to avoid saving properties.

**Comment by listelin** [comment]
ありがとうございます。
確かに、debug issueの値を変更後、startup fileを保存するとその値になりました。

この仕様自体はデバッグ条件が保存できて便利ですね。
動作上の実害はないのですが、KeyErrorのログが多く出るのが若干問題です。

再現手順
(1)debug issueを設定する
(2)Startup Fileを保存する
→　最初にdebug issueされた番号の画像KeyErrorになる

Indeed, after changing the value of the debug issue, saving the startup file resulted in that value.

This specification itself is useful for saving the debug conditions.
There is no real harm in the operation, but it is a little problematic to get a lot of KeyError logs.

Reproduction procedure
(1) Set the debug issue.
(2) Save the Startup File.
→ The image with the first debug issue number becomes a KeyError.
