### ISSUE TITLE
Asset search improvement ( auto reload , upper limit changable)

### ISSUE THREAD

**Issue by listelin** [UuuNyaa/blender_mmd_uuunyaa_tools#33]
アセットサーチについて以下2点改善してはどうでしょうか？

1. Blender起動時に自動的にasset jsonをupdate、reloadするオプションの追加
　プリファレンスでAuto update ON/OFFを選択可能に

2. 表示結果の上限を50固定から指定可能に

---
How about improving the following two points about asset search?

1. add option to automatically update/reload asset json when Blender is started.
　Auto update ON/OFF can be selected in preferences.

2. upper limit of display result can be set from 50

**Comment by UuuNyaa** [comment]
提案ありがとうございます。

> 2. 表示結果の上限を50固定から指定可能に

速度の問題から何らかの上限が必要だと考えています。何件が適切だと思いますか？



Thanks for the suggestion.

> 2. upper limit of display result can be set from 50

I think some upper limit is necessary due to performance issues. How many do you think is appropriate?

**Comment by listelin** [comment]
検討ありがとうございます

> > 1. 表示結果の上限を50固定から指定可能に
> 速度の問題から何らかの上限が必要だと考えています。何件が適切だと思いますか？

根拠のある数字ではありませんが200件程度でどうでしょうか。
無反応になるほど重くなければ変更すればいいだけなので
もしくは面倒でなければページ指定可能にしてもいいのかもしれません


> > 1. upper limit of display result can be set from 50
> I think some upper limit is necessary due to performance issues. How many do you think is appropriate?

I don't have a baseline number, but how about around 200?
If it's not so heavy that it becomes unresponsive, we can just change it.
Or, if it's not too much trouble, you could make it possible to specify pages.

**Comment by UuuNyaa** [comment]
Supported in v0.7.1.
Please test it.

**Comment by listelin** [comment]
Thank you.
I tested it and it's OK.

However, I think Asset JSON Auto Update on Startup should be ON by default.
Not many people read the documentation, and they usually expect the search button to return the latest results.
(Probably the only person who prefers the default OFF is me, who does a lot of debugging.

Please consider this for the next update.

---
ありがとう
テストしてOKでした

ただ、Asset JSON Auto Update on Startupは、デフォルトでONが良いと思います。
ドキュメントを読む人は少なく、通常検索ボタンを押せば最新の結果が帰ってくると期待すると思うので
（おそらくデフォルトOFFがよいのは、デバッグを多用する私だけな気がします）

次回更新の際にご検討ください

**Comment by listelin** [comment]
Thank you !
I confirmed that default is ON with 0.7.2
