### ISSUE TITLE
Changing Asset JSON Folder will cause an error

### ISSUE THREAD

**Issue by listelin** [UuuNyaa/blender_mmd_uuunyaa_tools#36]
マイナーなバグですが一応報告します。
Asset JSON Folderを変更すると以下のエラーになります。
```
location: <unknown location>:-1
エラー: Python: Traceback (most recent call last):
  File "C:\Users\a\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\mmd_uuunyaa_tools\asset_search\operators.py", line 56, in execute
    with open(os.path.join(PACKAGE_PATH, 'asset_jsons', self.output_json), mode='wt', encoding='utf-8') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\a\\AppData\\Roaming\\Blender Foundation\\Blender\\2.93\\scripts\\addons\\mmd_uuunyaa_tools\\asset_jsons\\assets.json'

location: <unknown location>:-1
```

再現手順
　uuunyaa_toolsを削除
　uuunyaa_toolsをインストール
　Asset JSON Folder設定を変更
　Update Assets JSONを押す

また、一旦デフォルトのAsset JSON FolderでUpdate Assets JSONを押して、その後Asset JSON Folderを変更すると
asset.jsonファイルはデフォルトの場所にあるのでエラーになりませんが、更新が反映されず検索結果がゼロになります。

---

This is a minor bug, but I'd like to report it.
When I change the Asset JSON Folder, I get the following error.
````
location: <unknown location>:-1
Error: Python: Traceback (most recent call last):
  File "C:\Users\a\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\mmd_uuunyaa_tools\asset_search\operators.py", line 56, in execute
    with open(os.path.join(PACKAGE_PATH, 'asset_jsons', self.output_json), mode='wt', encoding='utf-8') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\ Users\\AppData\\ Roaming\Blender Foundation\\\Blender\2.93\scripts\addons \\mmd_uuunyaa_tools\\\asset_jsons\\\assets.json'

location: <unknown location>:-1
````

Steps to Reproduce
　Delete uuunyaa_tools
　Install uuunyaa_tools
　Change Asset JSON Folder settings
　Press "Update Assets JSON

Also, if you press Update Assets JSON with the default Asset JSON Folder and then change the Asset JSON Folder
The asset.json file is in the default location, so there will be no error, but the update will not be reflected and the search result will be zero.

**Comment by UuuNyaa** [comment]
Maybe fixed this issue with #33.

**Comment by listelin** [comment]
I've confirmed that it's been fixed.
Thank you.
