### ISSUE TITLE
Asset search import function with 7-zip (Windows)

### ISSUE THREAD

**Issue by RAZUMNO** [UuuNyaa/blender_mmd_uuunyaa_tools#49]
I tried download and import some models ([Jean](https://github.com/UuuNyaa/blender_mmd_assets/issues/62) and [Eula](https://github.com/UuuNyaa/blender_mmd_assets/issues/91)) and got this error 
![blender_NGYgzUGa3G](https://user-images.githubusercontent.com/10924780/126733821-2f5ce774-85e1-48ba-9988-667608222a5b.png)
Of course I have installed 7-zip from official site. And i tried manually set PATH
![SystemPropertiesAdvanced_jGLPOJWrjJ](https://user-images.githubusercontent.com/10924780/126733926-140e7888-1747-4f1d-a610-6b5d8559429d.png)

**Comment by listelin** [comment]
1. Try 7z from comannd prompt
If normal, the output will look like this
![7z](https://user-images.githubusercontent.com/44924233/126741568-09dc3522-32c7-4355-a7bc-4c37f209cff5.jpg)

2.  Can you show me the system console log messages of Blender (menu Window > Toggle System Console) ?

**Comment by RAZUMNO** [comment]
1. Yeah, looks the same
2. I just try doing the same and it works. Looks like i needed restart my system after change system PATH. Strange. I was thinking PATH applies on the fly. And for me I change PATH manually, it's not applying by default. =\
