### ISSUE TITLE
Can't enable after install

### ISSUE THREAD

**Issue by FT001** [UuuNyaa/blender_mmd_uuunyaa_tools#51]
After installing add-on, I can't enable it.
It gives an error.

![Screenshot (1873)](https://user-images.githubusercontent.com/90799888/133504021-d709cca2-dc95-4c39-9326-780a60a7944f.png)

**Comment by listelin** [comment]
To use uuunyaa_tools, you need to install mmd_tools first.

Note: Unlike normal add-ons, mmd_tools cannot be installed straight from the downloaded zip file.

1 Download from here
https://github.com/powroupi/blender_mmd_tools/archive/dev_test.zip
2 Unzip and zip the generated mmd_tools folder
　Ignore the unzipped README, samples, etc.
3 Install the mmd_tools zip file

---
uuunyaa_toolsを使うには、先にmmd_toolsをインストールする必要があります

注意： mmd_toolsは通常のアドオンと違いダウンロードしたzipファイルをそのままインストールできません。

1 ここからダウンロード
https://github.com/powroupi/blender_mmd_tools/archive/dev_test.zip
2 解凍して生成されたmmd_toolsフォルダをzip圧縮する
　解凍されたREADMEやsamplesなどは無視してください
3 そのmmd_tools zipファイルをインストールする

**Comment by UuuNyaa** [comment]
Since the same problem is often reported, I wrote an article: [Why can't I use MMD UuuNyaa Tools?](https://mmd-blender.fandom.com/wiki/Why_can%27t_I_use_MMD_UuuNyaa_Tools%3F)

**Comment by FT001** [comment]
Thanks I installed and enabled it:)
