### ISSUE TITLE
Bone Name incompatible with Miku_Miku_Rig

### ISSUE THREAD

**Issue by CGMikeG** [UuuNyaa/blender_mmd_uuunyaa_tools#52]
Hello, I am not sure if you are able to fix this. I was playing with Miku_Miku_Rig AddOn to see if I can use his on and yours together.   What I did is I try to generate a rig from MMD using Miku_Miku_Rig, then I thought maybe I can convert that rig to an MMD compatible Rig just out of curiosity. Unfortunately, I keep getting an error because his rig's naming convention is different from yours. I think it was the bones that has the prefix OSR on the front. At one point I thought I can just rename the bones manually which was fine at the beginning until I got to the face. After that, I got overwhelmed. I thought I can't do this every time I am working on a new character. I am sure this will be time-consuming so I can understand if you can't fix but I just have to have to ask :D if you can update your add on so it can also convert Miku_Miku_Rig to be MMD compatible :) Thanks.

**Comment by UuuNyaa** [comment]
The armature converted with Miku_Miku_Rig should be MMD compatible.
So there is no need to convert it to MMD compatible using my addon.

"MMD compatible" means that MMD motion can be loaded.

Is my understanding wrong?

**Comment by CGMikeG** [comment]
I have tested Miku_Miku_Rig, in most cases, it works fine but for some reason when I convert VMD to NLA the legs don't move as expected. It's almost like it is lock in place, but strangely enough, it works fine when imported as VMD motion data. But I guess this is an issue more on Miku_Miku_Rig than your one. :D

**Comment by UuuNyaa** [comment]
Hmmm, I think using two add-ons at the same time is likely to cause problems.
What features do you want to use in Miku_Miku_Rig?
What is missing from my add-on?
