### ISSUE TITLE
likely not compatible with blender 3.0

### ISSUE THREAD

**Issue by 2Dimm** [UuuNyaa/blender_mmd_uuunyaa_tools#58]
trying to enable the addon in blender 3.0 give me a few errors, i can use the addon normally on 2.93 and bellow

![image](https://user-images.githubusercontent.com/20032676/140188205-62b2f9a1-057d-419e-b679-72376fdae867.png)

**Comment by UuuNyaa** [comment]
Thanks for testing in the Blender 3.0.
I added a workaround in v1.1.7 .
Could you please test it?

**Comment by RyougiShiki-214** [comment]
Thanks for the splendid addon, however this issue still exist in v1.1.19
![image](https://user-images.githubusercontent.com/53418317/142807208-4ce7b302-e497-49e7-8cdc-0a260517f55f.png)
