### ISSUE TITLE
Add metarig MMD to Rigify error 

### ISSUE THREAD

**Issue by SeulLip** [UuuNyaa/blender_mmd_uuunyaa_tools#63]
![image](https://user-images.githubusercontent.com/94801981/142774731-13e8c74f-4e4d-4b75-a56a-794274c7df4e.png)

When I press add metarig I get that error pop up and the rig is bigger than model, is it because bone structure is unsupported or I did something wrong? I don't know coding but maybe this is common issue?

**Comment by UuuNyaa** [comment]
> is it because bone structure is unsupported or I did something wrong?

The cause of this error is an unsupported bone structure.
Perhaps the model does not have "左肩" or "肩.L" bone.
Can you share the model with me to reproduce the problem?

**Comment by SeulLip** [comment]
https://www.deviantart.com/jerememez/art/MMD-Arcane-VI-WildRift-DOWNLOAD-898010041 is it okay with link to it?

**Comment by UuuNyaa** [comment]
I found a workaround.
Try editing the MMD bone names as follows:

```
L_Hip -> 左足
L_KneeLower -> 左ひざ
R_Hip -> 右足
R_KneeLower -> 右ひざ
```

https://user-images.githubusercontent.com/70152495/142779151-4edfe831-09af-45c2-a18d-ca3ed6fb831e.mp4

**Comment by SeulLip** [comment]
Aah thank you so much! :D
