### ISSUE TITLE
MMD UuuNyaa Material  don't show preview image

### ISSUE THREAD

**Issue by pencail** [UuuNyaa/blender_mmd_uuunyaa_tools#65]
MMD UuuNyaa Material  don't show preview image, blender Version is 2.91
![QQ截图20211227200225](https://user-images.githubusercontent.com/21018076/147470024-61ccbefb-b16b-41f9-908a-d9450917f8e2.png)

**Comment by UuuNyaa** [comment]
The following page may be useful to you.
https://mmd-blender.fandom.com/wiki/Why_can%27t_I_use_MMD_UuuNyaa_Tools%3F#Material_or_Lighting_icons_are_not_displayed

**Comment by UuuNyaa** [comment]
Same as #51

**Comment by pencail** [comment]
> 与[#51相同](https://github.com/UuuNyaa/blender_mmd_uuunyaa_tools/issues/51)

thank you
