### ISSUE TITLE
uuunyaa lighting shows nothing(black)

### ISSUE THREAD

**Issue by gurenFo** [UuuNyaa/blender_mmd_uuunyaa_tools#66]
selections can be pick, but no effect at all, perhaps hardware requirement is higher? im very new to mmd, still using some potato pc. 
[https://drive.google.com/file/d/10NYWiqwClIST4u-Sw6jzfNPqjXwe1qO9/view?usp=sharing](url)
[https://drive.google.com/file/d/1QdEVIby6kkxvipW_ESccaE8MzBpc1818/view?usp=sharing](url)

**Comment by UuuNyaa** [comment]
The following URL will help you.
https://mmd-blender.fandom.com/wiki/Why_can%27t_I_use_MMD_UuuNyaa_Tools%3F

#51 #55

**Comment by gurenFo** [comment]
solved, tq so much, sry for asking dumb question, again, thanks for your amazing addon!
