### ISSUE TITLE
Add addons is not responding

### ISSUE THREAD

**Issue by forkerrun** [UuuNyaa/blender_mmd_uuunyaa_tools#68]
![image](https://user-images.githubusercontent.com/49265188/150128859-a4a3856a-20a0-44ea-bc02-7dc01e7164c1.png)

**Comment by forkerrun** [comment]
blender version 3.0

**Comment by UuuNyaa** [comment]
Perhaps your network access is slow.
**MMD UuuNyaa Tools** accesses [blender_mmd_assets](https://github.com/UuuNyaa/blender_mmd_assets/issues) during initialization to get assets.
