### ISSUE TITLE
Cannot add metarig 

### ISSUE THREAD

**Issue by kouribos** [UuuNyaa/blender_mmd_uuunyaa_tools#70]
I tried to add a metarig on multiple pmx files but no matter the case or the model it keeps showing this error; when i tried to edit the name of the head bone it creates the same error but on different bones.
![error](https://user-images.githubusercontent.com/99512873/153722364-cf64ef4c-e345-4da0-b03d-e7d0df06bee1.PNG)
![error2](https://user-images.githubusercontent.com/99512873/153722586-5091a90b-ffe2-461a-8795-1fb17ad2539b.PNG)

**Comment by UuuNyaa** [comment]
It appears that the target model does not have bones with the correct MMD names.
Please check if there are any "首" (neck) or "右親指２" (right thumb 2) bones and rename them appropriately.

**Comment by kouribos** [comment]
yeah that's actually it and the sad part is that the whole rig has wrong names for every bone...
soo i am guessing that i have to rename the whole rig manually;
