### ISSUE TITLE
Rigify to MMD error

### ISSUE THREAD

**Issue by morring** [UuuNyaa/blender_mmd_uuunyaa_tools#71]
When I try to use the option to convert Rigify to MMD compatible I get this error: 
![image](https://user-images.githubusercontent.com/11776889/156305315-2b5261ad-6cbe-40ef-98bd-4dba15a37a25.png)

this is the model:
[Hiro.zip](https://github.com/UuuNyaa/blender_mmd_uuunyaa_tools/files/8167031/Hiro.zip)

**Comment by UuuNyaa** [comment]
It appears that the target model does not have bones with the correct Rigify names.
Please rename all incorrect bone names to the correct names as follows:
```
thumb01.L -> thumb.01.L
thumb01.R -> thumb.01.R
thumb02.L -> thumb.02.L
thumb02.R -> thumb.02.R
...
ring01.L -> ring.01.L
ring01.R -> ring.01.R
ring02.L -> ring.02.L
ring02.R -> ring.02.R
ring03.L -> ring.03.L
ring03.R -> ring.03.R
...
```

**Comment by leitoga** [comment]
i have the same problem with auto rig pro
