### ISSUE TITLE
Error while adding meta rig to any model imported from koikatsu (KKBP plugin)

### ISSUE THREAD

**Issue by Caelumcis** [UuuNyaa/blender_mmd_uuunyaa_tools#73]
![image_2022-03-28_140958](https://user-images.githubusercontent.com/101941456/160394844-6484d914-469d-42aa-87ab-a0bce9757fc3.png)

impossible to convert the rig to mmd aswell

**Comment by UuuNyaa** [comment]
You need to rename all bones to match MMD specifications.
Once you create a translation dictionary, the Global Translation feature may help you.

![image](https://user-images.githubusercontent.com/70152495/161531820-f7263c5a-7af5-44a7-a3a9-9750f78a361a.png)
