### ISSUE TITLE
Blender addon error after update

### ISSUE THREAD

**Issue by Fulpagun** [UuuNyaa/blender_mmd_uuunyaa_tools#78]
![캡처](https://user-images.githubusercontent.com/64728089/172649759-bcefccec-e762-496d-86a1-d930ecd7142b.PNG)
Blender addon error after update

**Comment by UuuNyaa** [comment]
Please enable the Rigify add-on in Blender Preference.
![image](https://user-images.githubusercontent.com/70152495/172769650-89290749-2a88-4e41-a4a1-cbb7d06e61a4.png)
