### ISSUE TITLE
asset search error (when default codec cp932)

### ISSUE THREAD

**Issue by listelin** [UuuNyaa/blender_mmd_uuunyaa_tools#8]
mmd_uuunyaa_tools-v0.1.0をインストールすると以下のエラーとなりアセットサーチ機能が動作しません。

Traceback (most recent call last):
  File "C:\Users\xxx\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\mmd_uuunyaa_tools\asset_search\assets.py", line 287, in reload
    for asset in json.load(f)['assets']:
  File "C:\blender\blender-2.92.0-windows64\2.92\python\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
UnicodeDecodeError: 'cp932' codec can't decode byte 0x9e in position 442: illegal multibyte sequence
ContentCache.__init__: cache_folder=C:\Users\xxx\AppData\Local\Temp\mmd_uuunyaa_tools_cache, temporary_dir=C:\Users\xxx\AppData\Local\Temp\tmpmaqlytsf

環境はWindows10、Blender2.92と2.83.13で確認しました。

**Comment by listelin** [comment]
githubの利用方法があまり分かっておらず適切な使い方でなかったら申し訳ありません。

asset.py 286行を以下のように修正するとエラーは解消しました。
with open(json_path) as f:
↓
with open(json_path,encoding="utf-8_sig") as f:

**Comment by UuuNyaa** [comment]
@listelin 
v0.1.1で修正しました。
時間があるときにテストしてください。

Fixed in v0.1.1
Please test it when you have time.
