### ISSUE TITLE
UuuNyaa Physics I can't find it

### ISSUE THREAD

**Issue by Fulpagun** [UuuNyaa/blender_mmd_uuunyaa_tools#82]
(https://user-images.githubusercontent.com/64728089/182834811-3981386d-3577-452a-9b82-f463bb89c8ef.png)
UuuNyaa Physics I can't find it

**Comment by UuuNyaa** [comment]
Ummmm..., I don't know why UuuNyaa Physics panel  is not showing :thinking:
Please try reinstalling the add-on.
