### ISSUE TITLE
It doesn't follow the physics engine.

### ISSUE THREAD

**Issue by vnfvkrns** [UuuNyaa/blender_mmd_uuunyaa_tools#89]
(https://mmd-blender.fandom.com/wiki/Why_is_physics_broken%3F) I looked at this link, but couldn't find the answer, so I'd love for you to tell me how to solve it yourself.

https://user-images.githubusercontent.com/34183780/202852263-b4062521-4c18-49d9-8196-c3b0cd8b4c74.mp4

**Comment by UuuNyaa** [comment]
Are you playing back?
Physics is not work until during playback or after baking.

**Comment by vnfvkrns** [comment]
> Are you playing back? Physics will only work until during playback or after baking.

Is it possible to make it move when not playing?
